### PR TITLE
Aboutpage

### PR DESCRIPTION
**Pull request by dreirik**
This is a first version of the new about-page. From the content it is ready to be published but the navigation needs a better style. Also please check the syntax etc for correctness @weeman1337 @mxmehl 

The beginin of the page should include a navigation. See here:

Selection_011

This, however, looks ugly. My proposal is to have eacht point within a badge and then simply list them one after the other with 2-5 in a row, depending on screen size. 

I made another very ugly example here but I hope it helps to understand my words : D 

navigation-proposal

Of course it should be "real" badges that are as big as the words are. Also I tried out black and whit in this example but I think black works better.

### CODE REVIEW

**Comment by dreirik** [comment]
ok, I made a very ugly version from the CSS point of view to help understand what kind of menu I was thinking of. Here is a screenshot:
Selection_012

**Comment by weeman1337** [comment]
Here are some text suggestions

| current | suggestion | comment |
| --- | --- | --- |
|  We already suffer by new |  We already being suffered by new | |
| in many member states | in many EU member states | The EU has not been mentioned above yet |
| will develop in the next decade or the one after | is developing in the next decades |  |
| To grow  | Growing up | To grow is something doing in the garden I think |
| get to know and network with each other | get to know to and network with each other | |
| friendships with each | friendships between each | |
| about: contribute | about: contributing | |
| Easiest option is to simply | The easiest option is to simply | |
| *-a-thons, camps, festival, exhibitions | *-a-thons, camps, festivals, exhibitions  | |
| If you know about Free, Libre and/or Open Source Software event | If you know about a Free, Libre and/or Open Source Software event | |
|  our list, please contribute |  our list, please contribute. | |
| But detached from the actual naming | But apart from actual naming | |
| to the same software | to the same kind of software | |

**Comment by dreirik** [comment]
I included most of your suggestions.

also I updated the page a little bit and included a new section: privacy. I would be good to go now and we can improve from here on.

**Comment by dreirik** [comment]
This page now has a status reached that we can go improve on top of it. Next step is the integration of the page via link from the main page and cleaning up the index-page accordingly.

**Pull request merged**
