### PR TITLE
UI improvement

### PR DESCRIPTION
**Pull request by weeman1337**
* Another try to clean up the UI
* Aligning of headlines, spacing etc.
* Basically the UI state from https://test.foss.events/ applied to the current master
* Most text changes are only limitations of the line lengths

### CODE REVIEW

**Comment by weeman1337** [comment]
resolves #87

**Comment by dreirik** [comment]
I do not like so much the 100% width in the menu__divider in the top menu, maybe we could give it a try with 80%? Else I like it ,especially the font type looks way better and it can be merged.

**Comment by weeman1337** [comment]
The divider has the same width as the content

image

It may be subjectively but I think that makes look a bit more consistent from the top until the footer

image

If you still insist on the 80 % I will change it.

**Comment by dreirik** [comment]
yeah, I forgot about the over max-width of the body. I am fine with it and will merge it.

**Pull request merged**
