### PR TITLE
updating design of indiviudal event-pages

### PR DESCRIPTION
**Pull request by dreirik**
slightly updating the design of the event pages with our new criteria and rearragned order and appearance of some older criteria

### CODE REVIEW

**Comment by weeman1337** [comment]
What do these points mean?
* `Technical Liberties`
* `First Edition`

**Review by weeman1337 — APPROVED** [review]

**Comment by dreirik** [comment]
renamed "first edition" in "first edition held in", hope that makes in clear. 

regarding the technological liberties, see #173

**Comment by weeman1337** [comment]
> renamed "first edition" in "first edition held in", hope that makes in clear.

Nope.. still no clue. Maybe it makes sense with content ¯\\\_(ツ)_/¯

**Comment by weeman1337** [comment]
Does not make sense with content for me either

>  Technological liberties: Green

**Pull request merged**
